######################################################################
# Automatically generated by qmake (3.0) ven. nov. 15 08:50:21 2019
######################################################################

TEMPLATE = app
TARGET = Game
INCLUDEPATH += .
INCLUDEPATH += /usr/include/irrlicht

# Input
HEADERS += \
    projet/src/terrain.h

SOURCES += projet/src/main.cpp \
    projet/src/terrain.cpp

